config/routes.rb
Dxypherblog::Application.routes.draw do
  authenticated :user do
    root to: 'home#index', via: :get
  end
  root to: 'home#index', via: :get
  post 'home/contact', controller: :home, action: :contact
  devise_for :users

  namespace :admin do
    resources :articles, :categories
  end

  resources :categories, only: [:index]
  match "/blog/filter" => "articles#filter_by_category"
  match "/blog" => "articles#index"
  resources :articles, only: [:index, :show] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  match "/comment/signup" => "registrations#new"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
     can :manage, :all
    end
  end
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :comments_count, :content, :publish, :title, :category_ids, :published

  has_and_belongs_to_many :categories
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  validates :title, :uniqueness => { :case_sensitive => false }

  has_and_belongs_to_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author, :body, :user

  belongs_to :article, :counter_cache => true
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :articles
  has_many :comments

  validates_presence_of :name
  validates_uniqueness_of :email, case_sensitive: false
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  layout 'admin'
  respond_to :html, :json, :js
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
    @category_options = Category.all
  end

  def create
    @article = Article.new(params[:article])
    @article.save
    respond_with [:admin, @article]
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
    @category_options = Category.all
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])
    @article.save
    respond_with [:admin, @article]
  end

  def destroy
    @article = Article.find(params[:id]).destroy
    redirect_to action: "index"
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout 'admin'
  respond_to :html, :json
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    @category.save
    redirect_to action: "index"
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
    redirect_to action: "index"
  end

  def destroy
    @category = Category.find(params[:id]).delete
    redirect_to action: "index"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def categories
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to root_path, :alert => exception.message
  end

  after_filter :store_location

  def store_location
    # store last url as long as it isn't a /users path
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def after_sign_up_path_for(resource)
    session[:previous_url] || root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper

  def index
    @categories = Category.all
    @articles = Article.where(published: true).order("created_at DESC").page(params[:page]).per(5)
  end

  def show
    @article = Article.includes(:comments).find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    article = Article.find(params[:article_id])
    comment = article.comments.create(body: params[:comment][:body], user: current_user, author: current_user.name)
    redirect_to article_path(article)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    comment = Comment.find(params[:id])
    @article = comment.article
    comment.update_attributes(params[:comment])
    redirect_to article_path(@article)
  end

  def destroy
    comment = Comment.find(params[:id])
    @article = comment.article
    comment.destroy
    redirect_to article_path(@article)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "homepage"
  include ContactHelper

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  def filter_by_category
    if params[:category] != "all"
      category = Category.includes(:articles).find(params[:category])
      @title = category.title
      @articles = category.articles.where(published: true).order("created_at DESC").page(params[:page]).per(5)
    else
      @articles = Article.where(published: true).order("created_at DESC").page(params[:page]).per(5)
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
  def contact
    if params[:email] != '' # only spam bots will enter email in here.
      redirect_to root_path
    else
      @contact = {}
      @contact[:name] = params[:name]
      @contact[:email] = params[:email_2]
      @contact[:message] = params[:message]
      ContactMailer.contact_message(@contact).deliver
      flash[:notice] = "Thanks for contacting me."
      redirect_to root_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/articles/edit.html.haml
%legend Edit Article

= simple_form_for [:admin, @article], :html => { :class => 'form-horizontal' } do |f|
  = f.input :title, label: "Article Title", :input_html => { :class => "span9" }
  = f.input :content, label: "Content", :input_html => { :class => "span10" }
  = f.association :categories, :collection => @category_options, :as => :check_boxes, :item_wrapper_class => 'inline'
  = f.button :submit

= link_to 'Delete Article', admin_article_path, :confirm => 'Delete Article?', :method => :delete

app/views/admin/articles/index.html.haml
%h3.admin-title Admin - Articles
.span3
  .well
    .nav= link_to "Create New Article", new_admin_article_path
.span8
  %table.table.table-striped
    %thead
      %tr
        %th id
        %th Title
        %th Published?
        %th Publish
    %tbody
      - @articles.each do |article|
        %tr
          %td= article.id
          %td= link_to article.title, admin_article_path(article)
          %td{id: "article_#{article.id}"}
            - if article.published?
              Yes
            - else
              No
          %td
            = form_for [:admin, article], remote: true do |f|
              = f.check_box :published, as: :boolean
              - f.submit

app/views/admin/articles/new.html.haml
%legend Create New Article

= simple_form_for [:admin, @article], :html => { :class => 'form-horizontal' } do |f|
  = f.input :title, label: "Article Title", :input_html => { :class => "span9" }
  = f.input :content, label: "Content", :input_html => { :class => "span10" }
  = f.association :categories, :collection => @category_options, :as => :check_boxes, :item_wrapper_class => 'inline'
  = f.input :published, as: :boolean
  = f.button :submit

app/views/admin/articles/show.html.haml
%h1= @article.title
%div
  = @article.content.html_safe
= link_to "Edit Article", edit_admin_article_path

app/views/admin/articles/update.js.haml
- if @article.published?
  $('#article_#{@article.id}').html("Yes");
- else
  $('#article_#{@article.id}').html("No");

app/views/admin/categories/edit.html.haml
%legend Edit Category

= simple_form_for [:admin, @category] do |f|
  = f.input :title, label: "Category Title"
  = f.button :submit

= link_to "Delete Category", admin_category_path(@category), confirm: "Delete Category", method: :delete

app/views/admin/categories/index.html.haml
%h3.admin-title Admin - Categories
.span3
  .well
    .nav= link_to "Create New Category", new_admin_category_path
.span8
  %table.table.table-striped
    %thead
      %tr
        %th id
        %th Title
    %tbody
      - @categories.each do |category|
        %tr
          %td= category.id
          %td= link_to category.title, edit_admin_category_path(category)

app/views/admin/categories/new.html.haml
%legend Create New Category

= simple_form_for [:admin, @category] do |f|
  = f.input :title, label: "Category Title"
  = f.button :submit

app/views/articles/_blog_articles.html.haml
.span9
  %h3
    Viewing
    %i.icon-caret-right
    = "#{@title ||= "All"} articles"
  %ul.articles-list
    - @articles.each do |article|
      %article
        %header
          %h2.article-title= link_to article.title, article_path(article)
          %p.date-posted
            %i.icon-calendar
            = (article.created_at).strftime("%B %d, %Y")
        .article-content= truncate(article.content, length: 500).html_safe
        %p.full-article-link
          = link_to 'Read Full Article', article_path(article)
          |
          %i.icon-comment
          = pluralize(article.comments_count, "Comment")
      %hr


  = paginate @articles, :theme => 'twitter-bootstrap'

app/views/articles/_category_filter.html.haml
%ul.span2.categories.nav.navlist
  %h2.nav-header
    %i.icon-th-list
    Categories
  %li.active= link_to "All Articles", blog_filter_path(category: "all"), remote: true
  - @categories.each do |category|
    %li= link_to category.title, blog_filter_path(category: category), remote: true

app/views/articles/filter_by_category.js.haml
$('.articles_partial').html("#{escape_javascript(render :partial => 'blog_articles' )}");

app/views/articles/index.html.haml
= render "category_filter"
.articles_partial
  = render "blog_articles"

app/views/articles/show.html.haml
%h1.article-title= @article.title
.article-content
  = @article.content.html_safe
%hr
= link_to "Add Comment", '#add_comment'
%h4
  %i.icon-comment
  = pluralize(@article.comments_count, "Comment")
.article-comments
  %ul.comment-list
    - @article.comments.each do |comment|
      %li
        .image
          = image_tag avatar_url(comment.user), class: 'circular'
        %span.author
          = comment.author
        .time
          %i.icon-time
          = time_ago_in_words(comment.created_at)
          ago
        %p
          = comment.body
        - if can? :delete, comment
          = link_to "Delete Comment", article_comment_path(comment.article.id, comment.id), confirm: "Delete Comment?", :method => :delete
        - if current_user == comment.user
          = link_to "Edit Comment", edit_article_comment_path(comment.article.id, comment.id)
  %span#add_comment
  - if current_user
    = render "comments/new_comment"
  - else
    %p.add-comment
      To add a comment please 
      = link_to "Sign Up", new_user_registration_path
      or
      = link_to "Login", new_user_session_path
      thanks!

app/views/comments/_new_comment.html.haml
= simple_form_for([@article, @article.comments.build]) do |f|
  = f.input :body, label: false, placeholder: "Type your comment here."
  = f.button :submit, "New Comment", :class => 'btn-primary'

app/views/comments/edit.html.haml
%legend Edit Comment

= simple_form_for([@comment.article, @comment], :html => { :class => 'form-horizontal' }) do |f|
  = f.input :body, label: "Comment Body", :input_html => { :class => "span9" }
  = f.button :submit, class: 'btn-primary'

= link_to "Delete Comment", article_comment_path(@comment.article.id, @comment.id), confirm: "Delete Comment?", :method => :delete, class: "delete-link"

app/views/home/index.html.haml
.container-fluid
%section#intro
  .span7
    %p.greeting Hello
    %br
    %p.greeting 
      My Name is  
      %em Nikhil Hira
    %br
    %p.greeting 
      I'm a 
      %em Ruby on Rails
    %br
    %p.greeting Developer
    %br
    %p.greeting in
    %br
    %p.greeting 
      %em San Francisco
%section#about
  .span5
    %p.section-title ABOUT ME
    %p From learning to fly planes at the age of 19 to pursuing careers in finance and marketing, I've always loved the challenge and excitment of learning something new. My love of learning was one of the big reasons I decided to pursue my growing interest in development as a full time endeavor and it continues to fuel my drive forward.

    %p That drive led me from my home in Tampa Florida to Code Academy in Chicago, where for three months I built a foundation in full stack web development in Ruby on Rails. After attending Code Academy I moved to San Francisco where I joined the web team at thredUP.com, one of the leading startups in the online clothing consignment space. During my time there I helped build new features for the companies client facing app while continually adding to and sharpening my skills to bring more value to my team and company.

    %p
      I'm currently looking for a new opportunity to join a team of developers who value learning, growth and enjoy sharing knowledge amongst one another. If your team has room for a developer like me, please don't hesitate to 
      = link_to 'contact me.', anchor: "contact"
  .span3
    = image_tag('me.jpg', size: '285x285', alt: "Nikhil Hira")
%section#skills
  %p.section-title SKILLS
  .span12
    %ul.left
      %ul.icons
        %li
          %i.icon-road
        %li
          %i.icon-html5
        %li
          %i.icon-keyboard
        %li
          %i.icon-coffee
        %li
          %i.icon-chevron-right
      %li
        
        %strong Ruby on Rails:
        Doing full-stack development within a large code base.
      %li
        %strong HAML / HTML:
        Coding dynamic and static UI’s.
      %li
        %strong Pair Programming:
        Pairing with fellow developers to share knowledge and write efficient, bug-free code.
      %li
        %strong Javascript / Coffeescript:
        Integrating JS/CS to create dynamic and interactive UI’s.
      %li
        %strong Backbone:
        Limited but growing experience building front end functionality with BackBone.
    %ul.right
      %ul.icons.second-set
        %li
          %i.icon-ok
        %li
          %i.icon-css3
        %li
          %i.icon-sitemap
        %li
          %i.icon-code-fork
        %li
          %i.icon-refresh
      %li
        %strong RSpec:
        Understanding of TDD process using RSpec.
      %li
        %strong SASS / CSS3:
        Styling UI’s with an eye for detail and staying true to designs.
      %li
        %strong MySQL:
        Building new model schemas.
      %li
        %strong Git:
        Github, reviewing and making pull requests, Git branching strategies.
      %li
        %strong Agile Development:
        Working with Asana story backlogs, development sprints, scrum, and biweekly retro.
%section#contact
  %p.section-title
    %i.icon-envelope
    GET IN TOUCH
  .span5
    = form_tag "/home/contact" do
      = text_field_tag "name", nil, placeholder: "Name"
      %span#spam_email
        = text_field_tag "email", nil
      = text_field_tag "email_2", nil,  placeholder: "Email"
      = text_area_tag "message", nil, placeholder: "Message"
      = submit_tag "Send Message", class: 'btn btn-primary'
  .span5
    %p
      I'm currently looking to join a team of developers as an apprentice or junior developer. I love working with developers who are always learning and who enjoy sharing their knowledge with others. If your team has room for a developer like me please get in touch.

app/views/layouts/_admin_nav.html.haml
= link_to root_path, :class => 'brand' do
  D
  %span
    X
  YPHER
%ul.nav
  - if current_user.has_role? :admin
    %li
      = link_to 'Articles', admin_articles_path
    %li
      = link_to 'Categories', admin_categories_path

app/views/layouts/_homepage_nav.html.haml
= link_to root_path, :class => 'brand' do
  D
  %span
    X
  YPHER
%ul.nav
  %li
    = link_to "Top", anchor: "intro"
  %li
    = link_to 'Blog', blog_path
  %li
    = link_to 'About Me', anchor: "about"
  %li
    = link_to "Skills", anchor: "skills"
  %li
    = link_to 'Contact', anchor: "contact"
  %li
    = link_to 'http://www.linkedin.com/in/nikhilhira/' do
      %i.icon-linkedin-sign
  %li
    = link_to 'https://github.com/dxypher' do
      %i.icon-github-alt

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} &#215;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to root_path, :class => 'brand' do
	D
	%span
		X
	YPHER
%ul.nav
	%li= link_to 'Blog', blog_path
	- if user_signed_in?
		%li
			= link_to 'Logout', destroy_user_session_path, :method=>'delete'
	- else
		%li
			= link_to 'Login', new_user_session_path
	- if user_signed_in?
		%li
			= link_to 'Edit account', edit_user_registration_path
		- if current_user.has_role? :admin
			%li
				=link_to 'Admin', admin_articles_path
	- else
		%li
			= link_to 'Sign up', new_user_registration_path
	%li
		= link_to 'http://www.linkedin.com/in/nikhilhira/' do
			%i.icon-linkedin-sign
	%li
		= link_to 'https://github.com/dxypher' do
			%i.icon-github-alt

app/views/layouts/admin.html.haml
- content_for :container do
  = render 'layouts/admin_nav'
= render :template => 'layouts/application'

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:charset => "utf-8"}
		%meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
		%meta{:author => "Nikhil Hira"}
		%title= content_for?(:title) ? yield(:title) : "Nikhil Hira - Ruby on Rails"
		= stylesheet_link_tag    "application", :media => "all"
		= stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.css"
		= javascript_include_tag "application"
		= csrf_meta_tags
		= yield(:head)
	%body{class: "#{controller_name} #{action_name}"}
		- if controller_name == 'home'
			%a{:href => "https://github.com/dxypher/dxypherblog"}
				%img.github{:alt => "Fork me on GitHub", :src => "https://s3.amazonaws.com/github/ribbons/forkme_left_darkblue_121621.png", :height => '149', :width => '149'}
		%header.navbar.navbar-fixed-top
			%nav.navbar-inner
				.container
					= content_for?(:container) ? yield(:container) : render('layouts/navigation')
		#main{:role => "main"}
			%div{class: "#{controller_name == 'home' ? 'container-fluid' : 'container'}"}
				.content
					%div{class: "#{controller_name == 'home' ? 'row-fluid' : 'row'}"}
						.span12
							= render 'layouts/messages'
							= yield
						%footer

app/views/layouts/homepage.html.haml
- content_for :container do
  = render 'layouts/homepage_nav'
= render :template => 'layouts/application'